### ISSUE TITLE
labelling chests so same item types would be in same chest

### ISSUE THREAD

**Issue by Polarite** [samolego/ClientStorage#28]
like Wood products going in wood labeled chest. Long shot but would be nice to use when played with other people using same chests!

**Comment by samolego** [comment]
I have thought about this but my proposal would be to use the chest presets -> like when you "input" wooden planks, a chest preset with free slot wanting wooden planks is found and is sent there ... It's not the best sollution, but works to some extent ...

The method you suggested (with naming) would be kinda hard to achieve, since it's hard to determine what "wood" is.

**Comment by Polarite** [comment]
maybe splitting with how is it breakable, like breaking tool, sort through dropping variant, like ores drop raw versions, stone types drop cobblestone, kinda a far stretch but I sadly have no better idea.

**Comment by samolego** [comment]
This would be quite complicated tbf ... Not impossible, but I'd rather spend time on other features ... Sorry.
